In [5]:
def classificateWithNumbersThreeTarget(value):
    target=0
    if(value>=0.0015):
        target=1
    elif(value<=-0.0015):
        target=-1
    else:
        target=0
    return target




def graph(test_y,yhat,mennyiseg,oszlop):
    valos=test_y[:,oszlop-1][:mennyiseg]
    predikt=yhat[:,oszlop-1][:mennyiseg]
    valos = pd.DataFrame(valos, columns=['Real'])
    predikt = pd.DataFrame(predikt, columns=['Predicted'])
    merge=valos.join(predikt)
    
    plt.figure(figsize=(30,20))
    sns.lineplot(data=merge, linewidth=3)
    plt.show()

def correlation_heatmap(df):
    correlations = df.corr()

    fig, ax = plt.subplots(figsize=(40,40))
    sns.heatmap(correlations, vmax=1.0, center=0, fmt='.2f',
                square=True, linewidths=.1, annot=True, cbar_kws={"shrink": .7})
    sns.set(font_scale=2)
    plt.show();
    
    
    
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

def metrikak(y_true,y_pred):
    print(mean_squared_error(y_true,y_pred))
    print(mean_absolute_percentage_error(y_true,y_pred))
from numpy import hstack
import array
from numpy import array
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')
print("Setup Complete")
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file
import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

def percentChange(lastValue,secondLastValue):
        return round((float(lastValue)-secondLastValue)/abs(secondLastValue),6)


def kirajzoltatas(yhat,test_y):
    yhat = pd.DataFrame(yhat, columns=['Predicted'])
    test_y2 = pd.DataFrame(test_y, columns=['Real'])
    merge=test_y2.join(yhat)

    import seaborn as sns
    import matplotlib.pyplot as plt

    plt.figure(figsize=(30,20))
    sns.lineplot(data=merge[:100], linewidth=3)
    plt.show()

# split a univariate sequence into samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)



tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0,
    patience=0,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
)
    
#data1 = pd.read_csv('/home/balazs/Desktop/adathalmazok/btc_2012-2021/btc_split_data_part_06', sep=",", header=None)
#data1.columns = ["time", "open", "high", "low","close","volume",'drop1','drop2']

#data2 = pd.read_csv('/home/balazs/Desktop/adathalmazok/btc_2012-2021/btc_split_data_part_07', sep=",", header=None)
#data2.columns = ["time", "open", "high", "low","close","volume",'drop1','drop2']

#data3 = pd.read_csv('/home/balazs/Desktop/adathalmazok/btc_2012-2021/btc_split_data_part_08', sep=",", header=None)
#data3.columns = ["time", "open", "high", "low","close","volume",'drop1','drop2']

data4 = pd.read_csv('/home/balazs/Desktop/adathalmazok/btc_2012-2021/btc_split_data_part_09', sep=",", header=None)
data4.columns = ["time", "open", "high", "low","close","volume"]

#data= pd.concat([data1,data2,data3,data4], axis=0)
data=data4.dropna()
data=data[['time','open','high','low','close','volume']]
#data

#data=data4
    

Setup Complete


In [6]:
def percentChangeDF(close_values):
    output=[]
    for i in range(1,len(close_values)):
        percent=percentChange(close_values[i],close_values[i-1])
        output.append(percent)
    return output
    

In [7]:
def split_sequence_modified(sequence, n_steps_in):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        # check if we are beyond the sequence
        if end_ix+5 > len(sequence):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sum(sequence[end_ix:end_ix+5])
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [ ]:
lista=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18

In [ ]:
train_X, train_y = split_sequence_modified(lista, 3)

In [ ]:
train_y

In [ ]:
train_X

# elesben

In [8]:
values=percentChangeDF(data.close.values)

In [9]:
train=values[:int(len(values)*0.8)]
test=values[int(len(values)*0.8):]

In [10]:
train_X, train_y = split_sequence_modified(train, 15)

In [11]:
n_features = 1
train_X = train_X.reshape((train_X.shape[0], train_X.shape[1], n_features))

In [24]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3)
# This callback will stop the training when there is no improvement in  
# the validation loss for three consecutive epochs.  

model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(15, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mape')
history=model.fit(train_X, train_y, epochs=20, verbose=1, callbacks=[callback])
len(history.history['loss'])


Epoch 1/20
8871/8871 [==============================] - 103s 11ms/step - loss: 4236.7261
Epoch 2/20
8871/8871 [==============================] - 99s 11ms/step - loss: 2647.1990
Epoch 3/20
8871/8871 [==============================] - 99s 11ms/step - loss: 2493.7979
Epoch 4/20
8871/8871 [==============================] - 111s 13ms/step - loss: 2513.5940
Epoch 5/20
8871/8871 [==============================] - 96s 11ms/step - loss: 2477.0688
Epoch 6/20
8871/8871 [==============================] - 98s 11ms/step - loss: 2849.6685
Epoch 7/20
8871/8871 [==============================] - 96s 11ms/step - loss: 2543.3083
Epoch 8/20
8871/8871 [==============================] - 97s 11ms/step - loss: 2395.1958
Epoch 9/20
8871/8871 [==============================] - 97s 11ms/step - loss: 2680.2273
Epoch 10/20
8871/8871 [==============================] - 101s 11ms/step - loss: 2521.6565
Epoch 11/20
8871/8871 [==============================] - 98s 11ms/step - loss: 2560.2993


11

In [25]:
test_X, test_y = split_sequence_modified(test, 15)
n_features = 1
test_X = test_X.reshape((test_X.shape[0], test_X.shape[1], n_features))

#performance =model.evaluate(test_X,test_y)
#print (performance)
yhat = model.predict(test_X, verbose=0)

In [26]:
yhat

array([[8.0714475e-05],
       [8.0714475e-05],
       [8.0714475e-05],
       ...,
       [8.0714475e-05],
       [8.0714475e-05],
       [8.0714475e-05]], dtype=float32)

In [27]:
test_y

array([-0.007888, -0.006012, -0.005012, ...,  0.000432,  0.000352,
        0.001088])

# elesben2 

In [64]:
values=data.close.pct_change()[1:]
values=values.values

In [65]:
moded_values=[elem*1000 for elem in values]

In [66]:
moded_values

[-0.09700171816862113,
 0.2796810191534327,
 0.0,
 -0.06087293857404141,
 0.6603568196803522,
 -0.5588706276364874,
 0.6159268151013642,
 0.09485826937272179,
 -0.977359891129459,
 -1.3457005692396606,
 0.6365556552183627,
 0.028915941358453878,
 0.34698126301169196,
 -0.19923855771919463,
 -0.018585537354343096,
 -0.17243569026426098,
 0.9490762255890406,
 -0.41992140144397894,
 0.3344267574436621,
 0.04540079616499604,
 0.6407412375284416,
 -0.8640858889000791,
 -0.1651232800088387,
 -0.30449632694840023,
 0.49353754912129233,
 -0.22807111690859028,
 0.45727852184462847,
 -0.07015965448431416,
 0.09492854563286635,
 0.7552293441679403,
 -0.1701076523700218,
 0.40420330188739584,
 -0.5287564123311883,
 0.12993870193311885,
 0.0,
 -0.7300368936723478,
 0.7068370229881271,
 0.023716450245458987,
 -0.4330727335343232,
 0.08768364565914233,
 -0.48685943687287736,
 0.092878586016365,
 0.3126621999656187,
 0.6189395502371742,
 0.5154639175257714,
 -0.27202472952081447,
 0.6905536384960165,


In [67]:
train=moded_values[:int(len(moded_values)*0.8)]
test=moded_values[int(len(moded_values)*0.8):]

In [68]:
train_X, train_y = split_sequence(train, 10,1)

In [69]:
n_steps_in, n_steps_out = 10, 1
train_X, train_y = split_sequence(train, n_steps_in, n_steps_out)

n_features = 1
train_X = train_X.reshape((train_X.shape[0], train_X.shape[1], n_features))

In [70]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3)
# This callback will stop the training when there is no improvement in  
# the validation loss for three consecutive epochs.  
model = Sequential()

model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')
history=model.fit(train_X, train_y, epochs=20, verbose=1, callbacks=[callback])
len(history.history['loss'])

Epoch 1/20
8871/8871 [==============================] - 90s 10ms/step - loss: 1.4382
Epoch 2/20
8871/8871 [==============================] - 81s 9ms/step - loss: 1.4384
Epoch 3/20
8871/8871 [==============================] - 72s 8ms/step - loss: 1.4330
Epoch 4/20
8871/8871 [==============================] - 76s 9ms/step - loss: 1.4319
Epoch 5/20
8871/8871 [==============================] - 72s 8ms/step - loss: 1.4304
Epoch 6/20
8871/8871 [==============================] - 78s 9ms/step - loss: 1.4290
Epoch 7/20
8871/8871 [==============================] - 83s 9ms/step - loss: 1.4299
Epoch 8/20
8871/8871 [==============================] - 78s 9ms/step - loss: 1.4316
Epoch 9/20
8871/8871 [==============================] - 96s 11ms/step - loss: 1.4292


9

In [71]:
test_X, test_y = split_sequence_modified(test, 10)
n_features = 1
test_X = test_X.reshape((test_X.shape[0], test_X.shape[1], n_features))

#performance =model.evaluate(test_X,test_y)
#print (performance)
yhat = model.predict(test_X, verbose=0)

In [72]:
yhat


array([[ 0.03726914],
       [-0.04543309],
       [ 0.00923536],
       ...,
       [-0.01785691],
       [-0.06238171],
       [ 0.04845518]], dtype=float32)

In [73]:
test_y

array([4.24234149, 2.84319618, 2.05896229, ..., 0.43227508, 0.35193473,
       1.08778523])